### ISSUE TITLE
Theme update

### ISSUE THREAD

**Issue by milicavs** [Codeinwp/jadrowp#116]
We want to release a small theme update since it's been over eight months since the last one.

- Check the theme to see if there's anything that needs to get up to date.
- We can make some small improvements in design if needed - max 1 day of work.
- Change the footer copyright text from 'Copyright © 2024. All Rights Reserved.' to 'Jadro | Powered by WordPress' and have the word 'Jadro' link to https://wpshout.com/jadro/

**Comment by kafleg** [comment]
https://github.com/Codeinwp/jadrowp/pull/117

**Comment by milicavs** [comment]
Hey @JohnPixle 

I think that adding a couple of new style presets would be great.

**Comment by milicavs** [comment]
Released 1.0.2
